service: visma-serverless-course

provider:
  name: aws
  runtime: python3.9
  region: eu-west-1
  stage: api
  apiGateway:
    apiKeys:
    - testKey
  versionFunctions: false

frameworkVersion: '3'

functions:
  hello:
    handler: src.handler.hello
    events:
      - http:
          path: /hello
          method: get
          private: true
  calculator:
    handler: src.handler.calculator
    events:
      - http:
          path: /calculator
          method: put
          private: true
  bin_packing:
    handler: src.bin_packing.bin_packing_handler
    events:
      - http:
          path: /bin_packing
          method: post
          private: true


plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux