service: visma-serverless-course

provider:
  name: aws
  runtime: python3.9
  region: eu-west-1
  stage: api
  apiGateway:
    apiKeys:
    - testKey
  versionFunctions: false

frameworkVersion: '3'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
          private: true
  calculator:
    handler: handler.calculator
    events:
      - http:
          path: /calculator
          method: put
          private: true

